name: Deploy React Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout frontend code
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "PWD: $(pwd)"
          echo "Files:"
          ls-l
          echo ""
          echo "Git Status"
          git status || echo "Not a git repository"

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Deploy Frontend via AWS SSM
      - name: Deploy Frontend via AWS SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --region "${{ secrets.AWS_REGION }}" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy React frontend" \
            --parameters commands='[
              "cd /home/ssm-user/projects/frontend", 
              "export GIT_TRACE=1 GIT_TRACE_PERFORMANCE=1 GIT_TRACE_SETUP=1 GIT_TRACE_PACK_ACCESS=1 GIT_CURL_VERBOSE=1 GIT_SSH_COMMAND=\"ssh -vvv\"",
              "git fetch origin",
              "git pull origin main --verbose --progress", 
              "npm install",
              "npm run build",
              "sudo rm -rf /var/www/frontend/*",
              "sudo cp -rv build/* /var/www/frontend/",
              "sudo chown -R www-data:www-data /var/www/frontend",
              "sudo systemctl reload nginx"
            ]' --query "Command.CommandId" --output text)

            echo "SSM Command ID: $COMMAND_ID"

            aws ssm wait command-executed --region "${{ secrets.AWS_REGION }}" --command-id "$COMMAND_ID" --instance-id "${{ secrets.EC2_INSTANCE_ID }}"

          aws ssm get-command-invocation --region "${{ secrets.AWS_REGION }}" --command-id "$COMMAND_ID" --instance-id "${{ secrets.EC2_INSTANCE_ID }}" --query "StandardOutputContent" --output text

          aws ssm get-command-invocation --region "${{ secrets.AWS_REGION }}" --command-id "$COMMAND_ID" --instance-id "${{ secrets.EC2_INSTANCE_ID }}" --query "StandardErrorContent" --output text


